version: '3.9'

volumes:
  FG_db:
  FG_static:
  FG_media:

services:

  db:
    image: postgres:15.0-alpine
    env_file: ./.env
    volumes:
      - FG_db:/var/lib/postgresql/data/
    
  backend:
    build: ../backend/
    env_file: ./.env
    volumes:
      - FG_static:/app/static/
      - FG_media:/app/media/
    depends_on:
      - db
    
  frontend:
    build: ../frontend/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.22.1-alpine-slim
    ports:
      - "7000:80"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - FG_static:/var/html/static/
      - FG_media:/app/media/
    depends_on:
      - backend
      - frontend
    restart: always